sudo: required
services:
   - docker

before_install:
   - docker build -t azharw49/docker-react -f Dockerfile.dev . 

script:
   - docker run -e CI=true azharw49/docker-react npm run test    
language: generic    